from __future__ import annotations

from dataclasses import asdict, dataclass, field
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from book2mp3.presets import get_preset


def utc_now() -> str:
    return datetime.now(timezone.utc).isoformat()


def default_audiobook_metadata(
    *,
    title: str,
    backend: str,
    voice_id: str = "",
    voice_profile_id: str = "",
    author: str = "",
    narrator: str = "",
    language: str = "",
    genre: str = "Audiobook",
    comment: str = "",
    publisher: str = "",
    year: int = 0,
    subject: str = "",
    isbn: str = "",
    description: str = "",
) -> "AudiobookMetadata":
    resolved_narrator = narrator or voice_profile_id or voice_id or backend
    resolved_comment = comment or f"Generated by book2mp3 with backend {backend}"
    return AudiobookMetadata(
        title=title,
        album=title,
        artist=resolved_narrator,
        album_artist=resolved_narrator,
        narrator=resolved_narrator,
        author=author,
        genre=genre,
        language=language,
        comment=resolved_comment,
        publisher=publisher,
        year=int(year or 0),
        subject=subject,
        isbn=isbn,
        description=description or resolved_comment,
    )


@dataclass
class ChunkRecord:
    index: int
    text_file: str
    wav_file: str
    mp3_file: str
    chapter_index: int = 1
    chapter_title: str = ""
    status: str = "pending"
    error: str = ""
    updated_at: str = field(default_factory=utc_now)

    def to_dict(self) -> dict[str, Any]:
        return asdict(self)


@dataclass
class ChapterRecord:
    index: int
    title: str
    text_file: str
    chunk_start_index: int
    chunk_end_index: int
    output_file: str = ""

    def to_dict(self) -> dict[str, Any]:
        return asdict(self)


@dataclass
class AudiobookMetadata:
    title: str
    album: str
    artist: str
    album_artist: str
    narrator: str
    author: str
    genre: str
    language: str
    comment: str
    publisher: str = ""
    year: int = 0
    subject: str = ""
    isbn: str = ""
    description: str = ""

    def to_dict(self) -> dict[str, Any]:
        return asdict(self)

    @classmethod
    def from_dict(cls, payload: dict[str, Any] | None, *, fallback: "AudiobookMetadata") -> "AudiobookMetadata":
        data = fallback.to_dict()
        if payload:
            allowed_keys = set(data)
            data.update({key: value for key, value in payload.items() if key in allowed_keys and value is not None})
        return cls(**data)


@dataclass
class JobState:
    job_id: str
    title: str
    source_name: str
    source_type: str
    created_at: str
    updated_at: str
    status: str
    backend: str
    saved_profile_id: str
    saved_profile_name: str
    voice_id: str
    voice_profile_id: str
    preset_id: str
    priority: int
    output_mode: str
    target_part_minutes: int
    keep_wav: bool
    max_chars: int
    sentence_silence: float
    length_scale: float
    source_file: str
    extracted_file: str
    final_output_file: str
    final_output_files: list[str]
    block_reason: str
    audiobook_metadata: AudiobookMetadata
    manifest_file: str
    chapters_file: str
    chapters: list[ChapterRecord]
    chunks: list[ChunkRecord]
    device_mode: str = "cpu"
    processing_mode: str = "serial"
    processing_mode_reason: str = ""
    source_characters: int = 0
    estimated_total_seconds: float = 0.0
    estimated_remaining_seconds: float = 0.0
    estimated_confidence: str = "none"
    estimated_from_samples: int = 0
    actual_total_seconds: float = 0.0
    processing_started_at: str = ""
    processing_completed_at: str = ""
    auto_recovery_attempts: int = 0
    last_failure_category: str = ""
    failure_report_file: str = ""
    logs: list[str] = field(default_factory=list)

    def to_dict(self) -> dict[str, Any]:
        payload = asdict(self)
        payload["chapters"] = [chapter.to_dict() for chapter in self.chapters]
        payload["chunks"] = [chunk.to_dict() for chunk in self.chunks]
        payload["audiobook_metadata"] = self.audiobook_metadata.to_dict()
        return payload

    @classmethod
    def from_dict(cls, payload: dict[str, Any]) -> "JobState":
        payload = dict(payload)
        preset = get_preset(payload.get("preset_id", "balanced"))
        payload.setdefault("preset_id", preset.preset_id)
        payload.setdefault("sentence_silence", preset.sentence_silence)
        payload.setdefault("length_scale", preset.length_scale)
        payload.setdefault("output_mode", preset.output_mode)
        payload.setdefault("target_part_minutes", preset.target_part_minutes)
        payload.setdefault("saved_profile_id", "")
        payload.setdefault("saved_profile_name", "")
        payload.setdefault("voice_profile_id", "")
        payload.setdefault("final_output_files", [])
        payload.setdefault("block_reason", "")
        payload.setdefault("device_mode", "cpu")
        payload.setdefault("processing_mode", "serial")
        payload.setdefault("processing_mode_reason", "")
        payload.setdefault("source_characters", 0)
        payload.setdefault("estimated_total_seconds", 0.0)
        payload.setdefault("estimated_remaining_seconds", 0.0)
        payload.setdefault("estimated_confidence", "none")
        payload.setdefault("estimated_from_samples", 0)
        payload.setdefault("actual_total_seconds", 0.0)
        payload.setdefault("processing_started_at", "")
        payload.setdefault("processing_completed_at", "")
        payload.setdefault("auto_recovery_attempts", 0)
        payload.setdefault("last_failure_category", "")
        payload.setdefault("failure_report_file", "")
        fallback_metadata = default_audiobook_metadata(
            title=str(payload.get("title", "Audiobook")),
            backend=str(payload.get("backend", "piper")),
            voice_id=str(payload.get("voice_id", "")),
            voice_profile_id=str(payload.get("voice_profile_id", "")),
        )
        payload["audiobook_metadata"] = AudiobookMetadata.from_dict(
            payload.get("audiobook_metadata"),
            fallback=fallback_metadata,
        )
        final_output_file = str(payload.get("final_output_file", "") or "")
        output_dir = Path(final_output_file).parent if final_output_file else Path(".")
        payload.setdefault("manifest_file", str(output_dir / "manifest.json"))
        payload.setdefault("chapters_file", str(output_dir / "chapters.json"))
        payload["chapters"] = [ChapterRecord(**chapter) for chapter in payload.get("chapters", [])]
        for chunk in payload.get("chunks", []):
            chunk.setdefault("chapter_index", 1)
            chunk.setdefault("chapter_title", "")
        payload["chunks"] = [ChunkRecord(**chunk) for chunk in payload.get("chunks", [])]
        return cls(**payload)

    @property
    def completed_chunks(self) -> int:
        return sum(1 for chunk in self.chunks if chunk.status == "done")

    @property
    def total_chunks(self) -> int:
        return len(self.chunks)

    def append_log(self, message: str) -> None:
        self.logs.append(f"{utc_now()} {message}")
        self.updated_at = utc_now()

    def job_dir(self, jobs_root: Path) -> Path:
        return jobs_root / self.job_id

    @property
    def is_queue_candidate(self) -> bool:
        return self.status in {"queued", "prepared", "running"}

    @property
    def failed_chunks(self) -> list[ChunkRecord]:
        return [chunk for chunk in self.chunks if chunk.status == "failed"]

    @property
    def pending_chunks(self) -> list[ChunkRecord]:
        return [chunk for chunk in self.chunks if chunk.status != "done"]

    def stage_statuses(self) -> list[dict[str, str]]:
        source_exists = Path(self.source_file).exists()
        extracted_exists = Path(self.extracted_file).exists()
        chapter_files_exist = bool(self.chapters) and all(Path(chapter.text_file).exists() for chapter in self.chapters)
        chunk_files_exist = bool(self.chunks) and all(Path(chunk.text_file).exists() for chunk in self.chunks)
        chunk_audio_exists = any(Path(chunk.mp3_file).exists() or Path(chunk.wav_file).exists() for chunk in self.chunks)
        export_ready = bool(self.final_output_files)
        metadata_ready = Path(self.manifest_file).exists() and Path(self.chapters_file).exists()

        synthesis_status = "pending"
        synthesis_detail = f"{self.completed_chunks}/{self.total_chunks} Chunks fertig"
        if self.estimated_remaining_seconds > 0:
            synthesis_detail += f" | Restzeit ca. {self.estimated_remaining_seconds/60:.1f} min"
        if self.failed_chunks:
            synthesis_status = "failed"
            synthesis_detail = f"{len(self.failed_chunks)} Chunk(s) fehlgeschlagen"
        elif self.status == "blocked" and self.block_reason:
            synthesis_status = "blocked"
            synthesis_detail = self.block_reason
        elif self.total_chunks and self.completed_chunks == self.total_chunks:
            synthesis_status = "done"
        elif self.completed_chunks or self.status == "running":
            synthesis_status = "running"

        assembly_status = "pending"
        assembly_detail = "Noch keine Enddatei erzeugt"
        if self.output_mode == "segments" and chunk_audio_exists:
            assembly_status = "done"
            assembly_detail = "Segmentdateien werden direkt als Ausgabe genutzt"
        elif export_ready:
            assembly_status = "done"
            assembly_detail = f"{len(self.final_output_files)} Enddatei(en) erzeugt"
        elif synthesis_status in {"running", "done"} and self.status == "running":
            assembly_status = "running"

        export_status = "done" if export_ready or (self.output_mode == "segments" and chunk_audio_exists) else "pending"
        export_detail = (
            f"{len(self.final_output_files)} Exportdatei(en)"
            if self.final_output_files
            else "Noch keine Exportdateien"
        )

        return [
            {
                "stage": "import",
                "label": "Import",
                "status": "done" if source_exists else "missing",
                "detail": Path(self.source_file).name if source_exists else "Quelldatei fehlt",
            },
            {
                "stage": "extract",
                "label": "Extraktion",
                "status": "done" if extracted_exists else "pending",
                "detail": Path(self.extracted_file).name if extracted_exists else "Text noch nicht extrahiert",
            },
            {
                "stage": "chapters",
                "label": "Kapitel",
                "status": "done" if chapter_files_exist else "pending",
                "detail": f"{len(self.chapters)} Kapitel erkannt" if self.chapters else "Noch keine Kapitelstruktur",
            },
            {
                "stage": "chunking",
                "label": "Chunking",
                "status": "done" if chunk_files_exist else "pending",
                "detail": f"{self.total_chunks} Chunk-Dateien" if self.chunks else "Noch keine Chunk-Dateien",
            },
            {
                "stage": "synthesis",
                "label": "Synthese",
                "status": synthesis_status,
                "detail": synthesis_detail,
            },
            {
                "stage": "assembly",
                "label": "Zusammenführung",
                "status": assembly_status,
                "detail": assembly_detail,
            },
            {
                "stage": "metadata",
                "label": "Metadaten",
                "status": "done" if metadata_ready else "pending",
                "detail": "manifest.json und chapters.json vorhanden" if metadata_ready else "Manifest/Chapters fehlen noch",
            },
            {
                "stage": "export",
                "label": "Export",
                "status": export_status,
                "detail": export_detail,
            },
        ]
